# Generated by Django 2.0.4 on 2018-04-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img', verbose_name='id')),
                ('name', models.CharField(max_length=100, verbose_name='图片名称')),
            ],
            options={
                'verbose_name_plural': '单图',
                'verbose_name': '单图',
            },
        ),
    ]
