# Generated by Django 2.0.4 on 2018-04-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imgs',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False, verbose_name='id')),
                ('img', models.ImageField(upload_to='./imgs/', verbose_name='图片地址')),
                ('single', models.CharField(blank=True, max_length=20, null=True, verbose_name='图片名称')),
            ],
            options={
                'verbose_name_plural': '图片',
                'verbose_name': '多图',
            },
        ),
        migrations.CreateModel(
            name='Imgs_name',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=10, verbose_name='图片库名称')),
                ('imgs', models.ManyToManyField(related_name='imgs', to='imgs_db.Imgs', verbose_name='图片表')),
            ],
            options={
                'verbose_name_plural': '图片集',
                'verbose_name': '图片集',
            },
        ),
    ]
