# Generated by Django 2.0.4 on 2018-04-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FILE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=30)),
                ('name', models.FileField(upload_to='./file/')),
            ],
            options={
                'verbose_name_plural': '单文件',
                'verbose_name': '单文件',
            },
        ),
    ]
