# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-05 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='a',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=32)),
                ('img', models.ImageField(upload_to='img')),
                ('partner', models.CharField(blank=True, max_length=32, null=True)),
                ('timeS', models.DateField(blank=True, max_length=32, null=True)),
                ('timeE', models.DateField(blank=True, max_length=32, null=True)),
                ('brief', models.TextField(blank=True, max_length=32, null=True)),
                ('tech', models.TextField(blank=True, max_length=32, null=True)),
                ('show', models.TextField(blank=True, max_length=32, null=True)),
                ('SVN', models.URLField(blank=True, null=True)),
                ('Git', models.URLField(blank=True, null=True)),
                ('imgs', models.ImageField(upload_to='imgs')),
                ('file', models.FileField(blank=True, null=True, upload_to='./file/')),
            ],
        ),
        migrations.CreateModel(
            name='b',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=32)),
                ('img', models.ImageField(upload_to='img')),
                ('partner', models.CharField(blank=True, max_length=32, null=True)),
                ('timeS', models.DateField(blank=True, max_length=32, null=True)),
                ('timeE', models.DateField(blank=True, max_length=32, null=True)),
                ('brief', models.TextField(blank=True, max_length=32, null=True)),
                ('tech', models.TextField(blank=True, max_length=32, null=True)),
                ('show', models.TextField(blank=True, max_length=32, null=True)),
                ('SVN', models.URLField(blank=True, null=True)),
                ('Git', models.URLField(blank=True, null=True)),
                ('imgs', models.ImageField(upload_to='imgs')),
                ('file', models.FileField(blank=True, null=True, upload_to='./file/')),
            ],
        ),
        migrations.CreateModel(
            name='c',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=32)),
                ('img', models.ImageField(upload_to='img')),
                ('partner', models.CharField(blank=True, max_length=32, null=True)),
                ('timeS', models.DateField(blank=True, max_length=32, null=True)),
                ('timeE', models.DateField(blank=True, max_length=32, null=True)),
                ('brief', models.TextField(blank=True, max_length=32, null=True)),
                ('tech', models.TextField(blank=True, max_length=32, null=True)),
                ('show', models.TextField(blank=True, max_length=32, null=True)),
                ('SVN', models.URLField(blank=True, null=True)),
                ('Git', models.URLField(blank=True, null=True)),
                ('imgs', models.ImageField(upload_to='imgs')),
                ('file', models.FileField(blank=True, null=True, upload_to='./file/')),
            ],
        ),
    ]
