# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-17 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('pwd', models.CharField(max_length=16)),
                ('save', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='soft',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('version', models.CharField(blank=True, max_length=16, null=True)),
                ('img', models.ImageField(upload_to='img')),
                ('use', models.URLField(blank=True, null=True)),
                ('downFile', models.FileField(blank=True, null=True, upload_to='./soft/')),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('portrait', models.CharField(max_length=16)),
                ('QQ', models.CharField(blank=True, max_length=16, null=True)),
                ('blog', models.CharField(blank=True, max_length=16, null=True)),
                ('job', models.CharField(blank=True, max_length=16, null=True)),
                ('adept', models.CharField(blank=True, max_length=16, null=True)),
                ('other', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='a',
            name='imgs',
            field=models.ImageField(blank=True, null=True, upload_to='imgs'),
        ),
        migrations.AlterField(
            model_name='b',
            name='imgs',
            field=models.ImageField(blank=True, null=True, upload_to='imgs'),
        ),
        migrations.AlterField(
            model_name='c',
            name='imgs',
            field=models.ImageField(blank=True, null=True, upload_to='imgs'),
        ),
    ]
