# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-17 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0002_auto_20180417_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a',
            name='Git',
            field=models.URLField(blank=True, null=True, verbose_name='Git'),
        ),
        migrations.AlterField(
            model_name='a',
            name='SVN',
            field=models.URLField(blank=True, null=True, verbose_name='SVN'),
        ),
        migrations.AlterField(
            model_name='a',
            name='address',
            field=models.URLField(max_length=32, verbose_name='项目地址'),
        ),
        migrations.AlterField(
            model_name='a',
            name='brief',
            field=models.TextField(blank=True, max_length=32, null=True, verbose_name='项目简介'),
        ),
        migrations.AlterField(
            model_name='a',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='./file/', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='a',
            name='id',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='a',
            name='img',
            field=models.ImageField(upload_to='img', verbose_name='项目主图'),
        ),
        migrations.AlterField(
            model_name='a',
            name='imgs',
            field=models.ImageField(blank=True, null=True, upload_to='imgs', verbose_name='其他图'),
        ),
        migrations.AlterField(
            model_name='a',
            name='name',
            field=models.CharField(max_length=32, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='a',
            name='partner',
            field=models.CharField(blank=True, choices=[('M', 'javascript'), ('F', 'php')], max_length=32, null=True, verbose_name='参与者'),
        ),
        migrations.AlterField(
            model_name='a',
            name='show',
            field=models.TextField(blank=True, max_length=32, null=True, verbose_name='详细内容'),
        ),
        migrations.AlterField(
            model_name='a',
            name='tech',
            field=models.TextField(blank=True, max_length=32, null=True, verbose_name='技术要点'),
        ),
        migrations.AlterField(
            model_name='a',
            name='timeE',
            field=models.DateField(blank=True, max_length=32, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='a',
            name='timeS',
            field=models.DateField(blank=True, max_length=32, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='b',
            name='Git',
            field=models.URLField(blank=True, null=True, verbose_name='Git'),
        ),
        migrations.AlterField(
            model_name='b',
            name='SVN',
            field=models.URLField(blank=True, null=True, verbose_name='SVN'),
        ),
        migrations.AlterField(
            model_name='b',
            name='address',
            field=models.URLField(max_length=32, verbose_name='项目地址'),
        ),
        migrations.AlterField(
            model_name='b',
            name='brief',
            field=models.TextField(blank=True, max_length=32, null=True, verbose_name='项目简介'),
        ),
        migrations.AlterField(
            model_name='b',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='./file/', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='b',
            name='id',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='b',
            name='img',
            field=models.ImageField(upload_to='img', verbose_name='项目主图'),
        ),
        migrations.AlterField(
            model_name='b',
            name='imgs',
            field=models.ImageField(blank=True, null=True, upload_to='imgs', verbose_name='其他图'),
        ),
        migrations.AlterField(
            model_name='b',
            name='name',
            field=models.CharField(max_length=32, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='b',
            name='partner',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='参与者'),
        ),
        migrations.AlterField(
            model_name='b',
            name='show',
            field=models.TextField(blank=True, max_length=32, null=True, verbose_name='详细内容'),
        ),
        migrations.AlterField(
            model_name='b',
            name='tech',
            field=models.TextField(blank=True, max_length=32, null=True, verbose_name='技术要点'),
        ),
        migrations.AlterField(
            model_name='b',
            name='timeE',
            field=models.DateField(blank=True, max_length=32, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='b',
            name='timeS',
            field=models.DateField(blank=True, max_length=32, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='c',
            name='Git',
            field=models.URLField(blank=True, null=True, verbose_name='Git'),
        ),
        migrations.AlterField(
            model_name='c',
            name='SVN',
            field=models.URLField(blank=True, null=True, verbose_name='SVN'),
        ),
        migrations.AlterField(
            model_name='c',
            name='address',
            field=models.URLField(max_length=32, verbose_name='项目地址'),
        ),
        migrations.AlterField(
            model_name='c',
            name='brief',
            field=models.TextField(blank=True, max_length=32, null=True, verbose_name='项目简介'),
        ),
        migrations.AlterField(
            model_name='c',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='./file/', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='c',
            name='id',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='c',
            name='img',
            field=models.ImageField(upload_to='img', verbose_name='项目主图'),
        ),
        migrations.AlterField(
            model_name='c',
            name='imgs',
            field=models.ImageField(blank=True, null=True, upload_to='imgs', verbose_name='其他图'),
        ),
        migrations.AlterField(
            model_name='c',
            name='name',
            field=models.CharField(max_length=32, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='c',
            name='partner',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='参与者'),
        ),
        migrations.AlterField(
            model_name='c',
            name='show',
            field=models.TextField(blank=True, max_length=32, null=True, verbose_name='详细内容'),
        ),
        migrations.AlterField(
            model_name='c',
            name='tech',
            field=models.TextField(blank=True, max_length=32, null=True, verbose_name='技术要点'),
        ),
        migrations.AlterField(
            model_name='c',
            name='timeE',
            field=models.DateField(blank=True, max_length=32, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='c',
            name='timeS',
            field=models.DateField(blank=True, max_length=32, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='portrait',
            field=models.ImageField(max_length=16, upload_to=''),
        ),
    ]
