# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-17 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0003_auto_20180417_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b',
            name='partner',
            field=models.CharField(blank=True, choices=[('M', 'javascript'), ('F', 'php')], max_length=32, null=True, verbose_name='参与者'),
        ),
        migrations.AlterField(
            model_name='c',
            name='partner',
            field=models.CharField(blank=True, choices=[('M', 'javascript'), ('F', 'php')], max_length=32, null=True, verbose_name='参与者'),
        ),
    ]
